### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by nelsonic** [dwyl/decache#49]
Several of the `devDependencies` of this project are out-of-date:
https://david-dm.org/dwyl/decache?type=dev
![image](https://user-images.githubusercontent.com/194400/81522112-4a7bb500-9341-11ea-8f01-d7ca8aae5728.png)

Having a **`red`** badge reflects poorly on the project. https://www.npmjs.com/package/decache
![image](https://user-images.githubusercontent.com/194400/81522193-8b73c980-9341-11ea-9a00-dd2054c39df0.png)

Thankfully the only Dependency `callsite` is stable:
![image](https://user-images.githubusercontent.com/194400/81522207-97f82200-9341-11ea-9c3c-87e1cec4f63b.png)

So we don't need to change any of the `code` in `decache.js`. 

# Todo

+ [x] Create a new branch where we can test the updates to each dev dependency
+ [x] Update `modern-syslog` to `1.2.0` and re-run the tests to confirm they work.
+ [x] Update `tape` to `5.0.0` and re-run tests.
+ [x] Replace `istanbul` with `nyc`. For usage, see: https://github.com/dwyl/hapi-auth-jwt2/blob/4e168c22087398fc90998ce801ffe96b378a9537/package.json#L79-L111
+ [x] Create a Pull Request referencing this issue. 
+ [x] Update versions of Node.js in `.travis.yml` to reflect latest supported and LTS version 
see: https://github.com/dwyl/decache/issues/49#issuecomment-626460620

**Comment by nelsonic** [comment]
Build passes for a recent version of Node but fails for older (_no longer supported_) versions:
https://travis-ci.org/github/dwyl/decache/builds/685495532
![image](https://user-images.githubusercontent.com/194400/81523770-c3c9d680-9346-11ea-922a-ea5c970eb8bc.png)


Looks like we need to drop support for older versions of Node.js in `.travis.yml` ...
https://github.com/dwyl/decache/blob/501de25900f0a4c68aa8c388bc655f2d05e7ee26/.travis.yml#L3-L6

NYC is using ES2015 ... So we gotta drop older Node.js versions. 
Updating now.

**Comment by nelsonic** [comment]
For some reason CodeCov is reporting a _decline_ in coverage:
![image](https://user-images.githubusercontent.com/194400/81524346-bada0480-9348-11ea-9366-fdf62cdadc3f.png)

Going to try adding _all_ the files to the NYC "include" list. 💭

**Comment by nelsonic** [comment]
Pull Request: #50
