### ISSUE TITLE
Update README.md Badges

### ISSUE THREAD

**Issue by nelsonic** [dwyl/decache#52]
Sadly, this is the state of the badges in the `README.md` right now:

<img width="1251" alt="decache-badges-broken" src="https://user-images.githubusercontent.com/194400/143438427-9e7b52ff-b08f-47e0-9e03-245504477069.png">

# Todo:
+ [x] Replace Travis-CI with GitHub Actions CI 
  see: https://github.com/dwyl/learn-travis/issues/67
  Sample file for `JS` project::
  + https://github.com/dwyl/javascript-todo-list-tutorial/blob/master/.github/workflows/ci.yml
+ [x] Update Build Badge to use GitHub CI badge instead of Travis-CI! 
+ [x] Update dependencies badge
+ [x] Update hits badge
+ [x] Create PR: #53 
+ [x] Confirm working ... ⏳ 
+ [ ] Publish new "patch" version to `npm` to update the package page: https://www.npmjs.com/package/decache

<img width="1396" alt="decache-npm-badges-broken" src="https://user-images.githubusercontent.com/194400/143440176-2c151abd-37b8-4b6e-8b45-6e42d0848b14.png">

**Comment by nelsonic** [comment]
Deps badge:
```
[![dependency status](https://img.shields.io/librariesio/release/npm/decache?style=flat-square)](https://github.com/dwyl/decache/blob/master/package.json#L43)
```
[![dependency status](https://img.shields.io/librariesio/release/npm/decache?style=flat-square)](https://github.com/dwyl/decache/blob/master/package.json#L43)

**Comment by nelsonic** [comment]
PR: #53 assigned to @SimonLab for help with GitHub CI ... 🤞

**Comment by SimonLab** [comment]
I just merged the PR, issue ready to be tested :+1:

**Comment by nelsonic** [comment]
Appears to be working as expected:
![FC86A0D3-1F4F-4C03-9E65-FE514591F2A7](https://user-images.githubusercontent.com/194400/143684054-f4494ee0-7ca7-4042-b3b0-8feb12b80bf3.jpeg)

Thanks @SimonLab 👍🏻
