### ISSUE TITLE
Chore: Tidy Badges

### ISSUE THREAD

**Issue by nelsonic** [dwyl/decache#62]
At present the badges in this repo `README.md` has two badges that are "broken":
https://www.npmjs.com/package/decache
<img width="1253" alt="image" src="https://github.com/dwyl/decache/assets/194400/1691d092-72cb-4111-8a7a-c8e53061dde8">

# Todo

+ [x] update the badges so they are green again. 
  + [x] Build badge see: https://github.com/dwyl/phoenix-todo-list-tutorial/issues/63
  + [x] Code Climate: https://codeclimate.com/github/dwyl/decache/builds

@LuchoTurtle once these two micro tasks are complete, 
please take a quick look at all the open issues and see what can be done about them. 🙏

**Comment by LuchoTurtle** [comment]
This issue is still assigned to me, I assume because of code analysis. 

> @nelsonic I have the build badge working but the code analysis doesn't seem to have any snapshots.

[codeclimate.com/github/dwyl/decache/builds](https://codeclimate.com/github/dwyl/decache/builds)

Have you got any updates from this, @nelsonic ?

**Comment by nelsonic** [comment]
Yeah, this doesn't appear to be working ...

<img width="1214" alt="image" src="https://github.com/dwyl/decache/assets/194400/62cd60dd-f404-42f9-bae2-b020ae439ccd">

I've tried triggering the `refresh` several times and it does not update. ♻️ 

<img width="1214" alt="image" src="https://github.com/dwyl/decache/assets/194400/349e9699-cb96-4682-a5a4-191ee3355b2a">

Let's just disable (comment out) the button for now. ✂️

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/decache/pull/64

**Comment by LuchoTurtle** [comment]
Closing as #64 has been merged.

**Comment by nelsonic** [comment]
Almost ... ⏳ 
There's `#OneMoreThing` -> https://github.com/dwyl/decache/issues/65 1️⃣
