### ISSUE TITLE
Chore: Publish new (patch) version to update the homepage on NPM

### ISSUE THREAD

**Issue by nelsonic** [dwyl/decache#65]
As noted in #62 the homepage on NPM is looking un-loved:
https://www.npmjs.com/package/decache
<img width="1253" alt="image" src="https://github.com/dwyl/decache/assets/194400/1691d092-72cb-4111-8a7a-c8e53061dde8">

# Todo:

+ [x] @LuchoTurtle to confirm that he has an NPM account (with OTP enabled) and 
  + [x] share the handle so that we can add him as a maintainer. 
+ [x] Create new `patch` version of the package
+ [x] Publish new version

Best to do this while we're on the standup call so I can guide you through the steps. 🧑‍💻

**Comment by LuchoTurtle** [comment]
Here's my NPM account (and handle) 
https://www.npmjs.com/~luchoturtle

**Comment by nelsonic** [comment]
Cool. 
<img width="1201" alt="image" src="https://github.com/dwyl/decache/assets/194400/8e37f230-90c1-44f5-87d9-1fd368a8edf8">

Maintainer invited: https://www.npmjs.com/package/decache/access
<img width="1370" alt="image" src="https://github.com/dwyl/decache/assets/194400/d8fb3367-8fd1-4a30-85da-47625a08c5e4">

**Comment by nelsonic** [comment]
@LuchoTurtle I have a _manual_ process for publishing packages to NPM cause that's just how I've done it since like 2012 ... but if there's a _better_ way, please feel free to suggest it and if we can document it in https://github.com/dwyl/learn-devops

These are the steps I follow:

1. `git checkout main` then `git pull` then `git checkout -b 'update-package-readme-issue-#65'`
2. Open the `package.json` file in editor e.g. `vim package.json`
3. Update the version number in the `package.json` file e.g: 
https://github.com/dwyl/decache/blob/e8df2eb096cd23303a46f4adb2065a131f7bced6/package.json#L3

4.  Update the last digit e.g. from `4.6.1` -> `4.6.2` 
5. Save the file
6. Create a commit e.g: `git commit -am 'Bump version 4.6.1 -> 4.6.2 to update README.md see: #65'`
7. Create a new `git tag` (that is used for the release) e.g: `git tag -a 'v4.6.2' -m 'Update README.md #65'`
8. Push both the commit and the tag to GitHub: `git push && git push --tags`
9. Create a PR with the update.
10. Once the PR is merged, run: `npm publish` (in the directory of the project) and enter your OTP.

@LuchoTurtle please share your screen and follow these steps. 👨‍💻

**Comment by LuchoTurtle** [comment]
In https://github.com/LuchoTurtle/tweakpane-plugin-file-import, I use https://github.com/release-it/release-it, which essentially makes this process seamless, creates the tags and publishes the package on NPM.

Since we've published this, closing it off 👌

**Comment by nelsonic** [comment]
Cool. Welcome to the "millions of downloads per month" package maintainers club. You've joined the **`1%`**. 😜
